#funciones

##CREE UNA FUNCIÓN QUE RETORNE SI UN NÚMERO ES PRIMO O NO
##10 MINUTOS






#listas

##IDENTIFIQUE LA CANTIDAD DE VALORES QUE SE ENCUENTRA EN UNA LISTA CUANDO SE INGRESE UN VALOR:
##lista = ["APPLE", "SAMSUNG", "HUAWEI","OPPO", "APPLE","ZTE","HUAWEI","MAC"]
##valorBuscar = "XIAOMI" -> RESULTADO = 0
##USA FUNCIONES SI SE DESEA
##20 MINUTOS
